#travis-ci file

# the build machine is
# Ubuntu 12.04 LTS acc. to 
# http://docs.travis-ci.com/user/installing-dependencies/

language: cpp
compiler:
- gcc
- clang
before_install:
# g++4.8.1
- if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
- sudo apt-get update -qq
install:
# g++4.8.1
- if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
- sudo apt-get install cmake libboost-dev libboost-system-dev libboost-program-options-dev
- sudo apt-get install root-system
#before_script:
#- mkdir _build
#- cd _build
script:
- cmake .
- make -j4
- ./artus_core_test

